set_property PACKAGE_PIN J1 [get_ports {sda}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sda}]
set_property PACKAGE_PIN L2 [get_ports {scl}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {scl]}]
set_property PACKAGE_PIN H1 [get_ports {sda}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sda}]
set_property PACKAGE_PIN K2 [get_ports {scl}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {scl}]
set_property PACKAGE_PIN A14 [get_ports {sda}]
    set_property IOSTANDARD LVCMOS33 [get_ports{sda}]
set_property PACKAGE_PIN A16 [get_ports{scl}]
    set_property IOSTANDARD LVCMOS33 [get_ports{scl}]
set_property PACKAGE_PIN A15 [get_ports{sda}]
    set_property IOSTANDARD LVCMOS33 [get_ports{sda}]
set_property PACKAGE_PIN M18 [get_ports{sda}]
    set_property IOSTANDARD LVCMOS33 [get_ports{sda}]
set_property PACKAGE_PIN N17 [get_ports{scl}]
    set_property IOSTANDARD LVCMOS33 [get_ports{scl}]